apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-web-app
  labels:
    app: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      replica: blue
  template:
    metadata:
      labels:
        app: my-app
        replica: blue
    spec:
      containers:
      - name: my-app
        image: samirsingh123/web-image:1.0
        ports:
        - name: http
          containerPort: 3000
        startupProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
