apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: my-app
    replica: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30007