apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: samirsingh123/web-image:1.1
        volumeMounts:
        - name: config-data
          mountPath: /config
          readOnly: true
        ports:
        - containerPort: 3000
      volumes:
      - name: config-data
        configMap:
          name: web-config